import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'firebase_options.dart';
import 'theme/app_colors.dart';
import 'theme/app_theme.dart';
import 'screens/splash_screen.dart';

Future<void> main() async {
  // Make sure Flutter's bindings are ready before we do async work
  // (loading the .env file, initializing Firebase) prior to runApp().
  WidgetsFlutterBinding.ensureInitialized();

  // Load API configuration (base URL, API key) from the local .env
  // file before the app starts, so ApiService can use it right away.
  await dotenv.load(fileName: '.env');

  // Initialize Firebase using the config generated by the FlutterFire
  // CLI for this project (lib/firebase_options.dart). No auth or
  // Firestore usage yet - this just brings up the Firebase app.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Match the system status/navigation bars to the app's dark
  // background, with light icons so they stay readable.
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      statusBarBrightness: Brightness.dark,
      systemNavigationBarColor: AppColors.deepBackground,
      systemNavigationBarIconBrightness: Brightness.light,
    ),
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GirlStadium',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      home: const SplashScreen(),
    );
  }
}